### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by victornpb** [bonaysoft/notion-md-gen#2]
I tried to use this, but its not working for me, I'm not sure if I'm doing something wrong, can you give me some directions?

I cloned this repo to here https://github.com/victornpb/notion-md-gen/actions,

This is what I’m getting triggering the actions manually
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/3372598/167327152-9c3590da-2282-4c65-b252-190ad468f595.png">

The only things changed:
- notion.yml renamed GITHUB_TOKEN to GH_TOKEN because GitHub wouldn't allow me to create a secret containing "GITHUB"
- I created a secret with my notion account and only changed the database ID of one of my own.

**Comment by saltbo** [comment]
fork to test? notion.yml can't read the config notion-md-gen.yml of example, and no save path in root

The correct directory should like `example` with `.github`

**Comment by victornpb** [comment]
Yeah, I meant forked not cloned (oops)

this is my action: https://github.com/victornpb/notion-md-gen/blob/master/.github/workflows/notion.yml
should I move this file to the project root? https://github.com/victornpb/notion-md-gen/blob/master/example/notion-md-gen.yaml (its inside example already)

I believe the files are in the correct directories, I'm sorry if I got it wrong

**Comment by saltbo** [comment]
Yeah
