### ISSUE TITLE
Big brother, help

### ISSUE THREAD

**Issue by dc932dc** [bonaysoft/notion-md-gen#5]
@gwillem @saltbo @xzebra @rnakamine 

Guys, is there an action version of the GitHub warehouse template?
 I tried all afternoon and couldn’t figure it out. The foreigner said that he also failed. [iss](https://github.com/bonaysoft/notion-md-gen/issues/2)

**Comment by saltbo** [comment]
You can refer to my blog https://github.com/saltbo/blog/blob/master/.github/workflows/main.yml
